### ISSUE TITLE
TMS_script issue

### ISSUE THREAD

**Issue by XavierCorominas** [OpitzLab/NeMo-TMS#2]
Dear members of the OptizLab, 

First of all, I would like to thank you for having kindly provided oven access to your new modelling tool.
My name is Xavier and I am a PhD student in Paris(France) currently exploring the possibilities offered by your new toolbox. However, I am facing a bug that I do not manage to solve.

Following your guide, when I get to point 3.7 where the simulation starts, when I start the TMS_script.hoc function, I always get the same error:

"NEURON -- VERSION 8.2.0+ HEAD (156b9dee+) 2022-07-01
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2021
See http://neuron.yale.edu/neuron/credits
        1
loading membrane mechanisms from ../../lib_mech/nrnmech.dll
Additional mechanisms from files
 Ca.mod CaDynamics_E2.mod Ca_HVA.mod Ca_LVAst.mod Ih.mod Im.mod K_Pst.mod K_Tst.mod NMDA.mod NaTa_t.mod NaTg.mod NaTs2_t.mod Nap_Et2.mod ProbAMPANMDA_EMS.mod ProbGABAAB_EMS.mod SK_E2.mod SKv3_1.mod vecevent.mod xtra.mod
C:\nrn\bin\nrniv.exe: Can't open  init_pp.hoc
 in C:/NeMo-TMS-2_2/Models/Aberra_human_L5/Code/NEURON/TMS_script.hoc near line 14
 ^
        xopen("init_pp.hoc")
      TMS_sim()
oc>"

Could you please guide me to solve this error ?

Thank you very much in advance.
Xavier.

**Comment by Sinaxist** [comment]
Dear Xavier,
There could be several things that cause the issue. Please try the following to see if the problem is resolved. Afterward, we can pinpoint the potential cause.
1. Generate one of the Jarsky models as explained in 3.2
2. In step 3.7, When selecting simulation settings (`GUI_params.hoc`), choose the uniform electric field with default amplitude and orientation, and set the weights of random and synchronous synaptic inputs to 0.
3. Run the software packages (e.g. NEURON and MATLAB) with the versions described in the tutorial. I see that you used NEURON 8.2, while we developed the toolbox on NEURON 7.
If none of these helped, please make a zip file of the model you generated (`C:/NeMo-TMS-2_2/Models/Aberra_human_L5` folder) and send it to me at shiri008[at]umn.edu

**Comment by stellaaaaav** [comment]
Dear Sina,

 I wonder if this problem has been solved. I also get this issue.

**Comment by Sinaxist** [comment]
@VioletShift Can you take a look at this?

**Comment by Sinaxist** [comment]
@stellaaaaav I talked to my colleague and he mentioned that T2N has a dependency that seems to only arise in newer versions of MATLAB - on some versions newer than 2020b, it seems to require the "Statistics and Machine Learning Toolbox". Can you give that a try?

**Comment by stellaaaaav** [comment]
Thanks. It works now.

**Comment by stellaaaaav** [comment]
Hello, I have a question about the TMS waveform generation. It has two
inputs: interval and pulse number. However, how do I specify the pulse
width of each pulse?

**Comment by Sinaxist** [comment]
@stellaaaaav I moved this to a new issue since it is not relevant to the original issue.
